### PR TITLE
Feature/add paper links

### PR DESCRIPTION
**Pull request by ZacRavichandran**
Link papers to Google Drive pdfs

### CODE REVIEW

**Comment by lucacarlone** [comment]
@ZacRavichandran : did you merge with master before the PR? it seems the schedule is not up to date.

**Comment by ZacRavichandran** [comment]
No, just realized that I missed the updates. I'm fixing that now!

**Comment by lucacarlone** [comment]
thanks!

**Comment by ZacRavichandran** [comment]
ok, it should be up to date now.

**Review by lucacarlone — APPROVED** [review]

**Pull request merged**
